version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      DATABASE_URL: "jdbc:postgresql://postgres:5432/postgres"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
